blank_issues_enabled: true
contact_links:
  - name: 💬 Questions & Discussions
    url: https://github.com/Mozcko/algorithm-visualizer/discussions
    about: Please use this for general questions and discussions, not for bug reports.
